name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy Frontend to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # Create target directory if it doesn't exist
            mkdir -p /home/bakersburns/htdocs/bakersburns.com/
            # Sync frontend files to the VPS
            rsync -avz Frontend/registerFrontEnd/dist/ /home/bakersburns/htdocs/bakersburns.com/
            # Optionally, restart web server if needed
            sudo systemctl restart nginx

  deploy-backend:
    name: Deploy Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy Backend to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # Replace backend files with new ones
            rm -rf /home/bakersburns-api/backend/*
            rsync -avz Backend/ /home/bakersburns-api/backend/
            # Restart backend service
            sudo systemctl restart backend-service

  deploy-admin:
    name: Deploy Admin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy Admin to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # Create target directory if it doesn't exist
            mkdir -p /home/bakersburns-admin/htdocs/admin.bakersburns.com/
            # Sync admin frontend files to the VPS
            rsync -avz Frontend/adminFrontEnd/dist/ /home/bakersburns-admin/htdocs/admin.bakersburns.com/
            # Optionally, restart web server if needed
            sudo systemctl restart nginx

  deploy-user:
    name: Deploy User Interface
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy User Interface to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # Create target directory if it doesn't exist
            mkdir -p /home/bakersburns-user/htdocs/user.bakersburns.com/
            # Sync user frontend files to the VPS
            rsync -avz Frontend/userFrontEnd/dist/ /home/bakersburns-user/htdocs/user.bakersburns.com/
            # Optionally, restart web server if needed
            sudo systemctl restart nginx
