name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install --prefix Frontend/registerFrontEnd
      
      - name: Build Frontend
        run: npm run build --prefix Frontend/registerFrontEnd

      - name: Verify Source Directory
        run: ls -R Frontend/registerFrontEnd/dist/ || echo "Directory not found"
      - name: Debug Repository Files
        run: |
          echo "Listing all files..."
          ls -R Frontend/registerFrontEnd
      

      - name: Deploy Frontend to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # Ensure the target directory exists
            if [ ! -d /home/bakersburns/htdocs/bakersburns.com/ ]; then
              echo "Target directory does not exist: /home/bakersburns/htdocs/bakersburns.com/"
              exit 1
            fi
            # Sync frontend files to the existing directory
            rsync -avz Frontend/registerFrontEnd/dist/ /home/bakersburns/htdocs/bakersburns.com/
            
            

  deploy-backend:
    name: Deploy Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Verify Source Directory
        run: ls -R Backend/ || echo "Directory not found"

      - name: Deploy Backend to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # Ensure the target directory exists
            if [ ! -d /home/bakersburns-api/backend/ ]; then
              echo "Target directory does not exist: /home/bakersburns-api/htdocs/api.bakersburns.com/backend/
              "
              exit 1
            fi
            # Clear existing backend files and sync new ones
            rm -rf /home/bakersburns-api/backend/*
            rsync -avz  --exclude=".env" Backend/ /home/bakersburns-api/htdocs/api.bakersburns.com/backend/

            # Restart backend service
            pm2 restart bakersburns

  deploy-admin:
    name: Deploy Admin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Verify Source Directory
        run: ls -R Frontend/adminFrontEnd/dist/ || echo "Directory not found"

      - name: Deploy Admin to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # Ensure the target directory exists
            if [ ! -d /home/bakersburns-admin/htdocs/admin.bakersburns.com/ ]; then
              echo "Target directory does not exist: /home/bakersburns-admin/htdocs/admin.bakersburns.com/"
              exit 1
            fi
            # Sync admin frontend files
            rsync -avz Frontend/adminFrontEnd/dist/ /home/bakersburns-admin/htdocs/admin.bakersburns.com/
            

  deploy-user:
    name: Deploy User Interface
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Verify Source Directory
        run: ls -R Frontend/userFrontEnd/dist/ || echo "Directory not found"

      - name: Deploy User Interface to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # Ensure the target directory exists
            if [ ! -d /home/bakersburns-user/htdocs/user.bakersburns.com/ ]; then
              echo "Target directory does not exist: /home/bakersburns-user/htdocs/user.bakersburns.com/"
              exit 1
            fi
            # Sync user frontend files
            rsync -avz Frontend/userFrontEnd/dist/ /home/bakersburns-user/htdocs/user.bakersburns.com/
            
