name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy Frontend to VPS
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            mkdir -p /home/bakersburns/htdocs/bakersburns.com/
            rsync -avz ./frontend/registerFrontEnd/dist/ /home/bakersburns/htdocs/bakersburns.com/

  deploy-backend:
    name: Deploy Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy Backend to VPS
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            mkdir -p /home/bakersburns-api/backend/
            rsync -avz ./Backend/ /home/bakersburns-api/backend/

  deploy-admin:
    name: Deploy Admin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy Admin to VPS
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            mkdir -p /home/bakersburns-admin/htdocs/admin.bakersburns.com/
            rsync -avz ./frontend/adminFrontEnd/dist/ /home/bakersburns-admin/htdocs/admin.bakersburns.com/

  deploy-user:
    name: Deploy User Interface
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy User Interface to VPS
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            mkdir -p /home/bakersburns-user/htdocs/user.bakersburns.com/
            rsync -avz ./frontend/userFrontEnd/dist/ /home/bakersburns-user/htdocs/user.bakersburns.com/
